In [3]:
import torch
import torch.nn.functional as F
import numpy as np

In [44]:
torch.manual_seed(42)
out_channels = 3
in_channels =2
h=2
w=3
weight = torch.rand([out_channels, in_channels, h, w])

In [45]:
image = torch.eye(6)[None, None, :].expand(-1,in_channels, -1, -1)
print(image.shape, weight.shape)
out = F.conv2d(input=image, weight=weight)

torch.Size([1, 2, 6, 6]) torch.Size([3, 2, 2, 3])


In [51]:
torch.sum(weight, axis=(1,2,3))

tensor([7.7831, 6.8006, 5.1290])

In [56]:
print(torch.max(torch.abs(weight)))

print(torch.sum(torch.abs(weight), axis=(2,3)))
print(torch.sum(torch.abs(weight), axis=(1, 2,3)))
print(torch.sum(torch.abs(weight), axis=(0, 2,3)))

tensor(0.9593)
tensor([[4.1308, 3.6523],
        [4.0670, 2.7336],
        [1.4863, 3.6427]])
tensor([7.7831, 6.8006, 5.1290])
tensor([ 9.6841, 10.0286])


In [31]:
image = torch.eye(6).expand()

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])